[package]
name = "cross-fs"
version = "0.1.0"
edition = "2024"

[features]
align-512 = []
direct-io = []

[dependencies]
parking_lot = "0.12"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3.23"
